In [1]:
import pandas as pd
import sys
sys.path.append("./../src")
import utils

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
UK="./../data/ParlEE_UK_plenary_speeches.csv"

In [3]:
keywords={
        "nuclear": ["reactor", "fission", "fusion", "radioactive", "radiation", "waste disposal", "spent fuel", "uranium", "plutonium", "thorium", "enrichment", "decommissioning", "atomic energy", "power plant", "reactor core", "SMR", "Small Modular Reactor", "fuel cycle", "coolant", "containment"],
        "climate_change": ["global warming", "greenhouse gases", "carbon emissions", "renewable energy", "sustainability", "fossil fuels", "deforestation", "sea level rise", "climate policy", "carbon footprint", "emission reduction", "climate adaptation", "climate mitigation", "COP26", "Paris Agreement"],
    }

In [4]:
df=pd.read_csv(UK)
uk=utils.StanceDetector(df, keywords)

/var/folders/06/25_1mnt97hq60zy5672y3qzw0000gn/T/ipykernel_75459/3036835758.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(UK)

In [5]:
print(uk.format_discussion("Inquests [Oral Answers to Questions > Defence]", '12/01/2009'))

Rosie Cooper (Lab): What progress is being made in reducing the time taken to complete inquests on members of the armed forces killed on operations?
Bob Ainsworth (Lab): We have managed largely to eliminate the backlog of inquests. We have established the Defence Inquests Unit to lead our drive to improve co-ordination and support for families, coroners and others. However, some inquests, due to their complexity, will always take time, and it is only right that they are allowed to do so when necessary.
Rosie Cooper (Lab): I thank the Minister for that response, but perhaps he could tell us what lessons have been learned that will enable to us to continue to improve the service we give to the families of service personnel?
Bob Ainsworth (Lab): I have said to the House on previous occasions that one of my priorities in this job was to eliminate unnecessary delay, because it just adds to the pain and suffering of people who have lost their loved ones when we delay our inquiries, and often therefore the coroner's inquiries. We had to get on top of that, and we had to ensure that we eliminated such delay. We have done that over a period of time, and I am enormously pleased by that. We also need to look, as we are doing, at the level of service that we give to families when they have suffered a bereavement, to try to ensure that we give them the most professional support without breaking the vital link between the families and the individual regiments and units to which their loved ones belonged. That is also important.
Stewart Hosie (SNP): The Minister will be aware of the good progress made between the UK and Scottish Governments on ensuring that investigations can take place in Scotland into the deaths of service personnel who normally reside there, but I understand that some work remains to be done before that becomes a routine measure. What progress is being made and when is that likely to happen?
Bob Ainsworth (Lab): The hon. Gentleman may know that the then Secretary of State wrote to the Scottish Government in March last year on this issue. We eventually received a reply in November, and we will respond as soon as we are able to do so. I hope that that will be very shortly.
James Gray (Con): I pay particular tribute to the retiring Wiltshire coroner, David Masters, who has done a superb job in getting the backlog down and in carrying out very difficult inquests such as that into XV179, the Hercules that was downed in Iraq. In the town of Wootton Bassett in my constituency, we see the return of the bodies week by week. Surely it is time for the Government to consider something rather like the hon. Member for Dundee, East (Stewart Hosie) is suggesting with regard to Scotland. Rather than using local coroners in Oxfordshire and now in Wiltshire to carry out these difficult inquests, would it not be possible to have the inquests in the places where the servicemen are based?
Bob Ainsworth (Lab): First, let me join the hon. Gentleman in praising the work of the Wiltshire coroner, whose dedication and thoroughness in his work are quite tremendous and should be applauded. We attempt to have inquests undertaken in the local area wherever possible and we have made some progress in that. We do so overwhelmingly for the benefit of the families. It is not possible in Scotland, but we are looking to sort that out and hope to have the assistance of the Scottish Government in doing so. Mr. Masters has undertaken a lot of inquests, and on the odd occasion he has taken inquests back when it was felt that the expertise that he was able to apply would be more useful than a local inquest. He has been very constructive in that regard.
Robert Key (Con): Fallen service personnel are repatriated through Lyneham in the constituency of my hon. Friend the Member for North Wiltshire (Mr. Gray). The office and office staff, however, are in Salisbury. The retiring coroner said last week that he feared for the future of the coroner service in Wiltshire because a decision was made with no consultation to move the office and staff from Salisbury to Devizes, the excellent constituency of my right hon. and learned Friend the Member for Devizes (Mr. Ancram), who is in his place. The coroner fears that the expertise of those staff will be entirely lost. It is a complex and difficult situation involving relations with the military. Will the Minister undertake to look very closely at the future of the coroner service in Wiltshire to ensure that a service that serves the nation is not lost but, far from that, is enhanced?
Bob Ainsworth (Lab): I think that I ought to concentrate on trying to do my job as Minister for the Armed Forces rather than trying to run the coroner service as well. I would be worried if we lost the expertise. I am worried that we will lose the expertise that Mr. Masters has built up over time. He is due to retire, so that is possibly inevitable, but we need to try to keep that expertise. The hon. Gentleman laughs, but there is a possibility that we will not be able to retain Mr. Masters's services. I do not know whether that is the case, and it is not a matter for me. I would like us to do whatever we can to maintain the expertise that we have had, but it is not a matter for the MOD in the first instance.

In [6]:
nuclear_df=uk.filter_speeches('nuclear')

In [10]:
print(uk.format_discussion("Gaza", '21/01/2009'))

Clare Short (Independent): I am grateful for the opportunity to report to the House on my recent visit to Gaza. Also, I wish to press the Government to do more to uphold international law. It is my view, and that of many others, that if international law were upheld, there could and would be two states in Palestine, and we could look forward realistically to peace, but Israel constantly flouts international law, and the United States, the United Kingdom and the whole of the European Union collude in that. Thus, Israel concludes that might is right and uses its massive armaments to kill and bombard any who resist the constant expansion of its borders and land. Currently, we face the prospect of decades of bloodshed, conflict and bitterness in the middle east. We also see the authority of international law and the moral authority of the United Nations being eroded. That, alongside growing environmental strains and population growth in the poorest countries, promises a grim and disorderly future if we continue on the path that we are on. I reported briefly in the topical debate on Thursday 15 January on my visit to Gaza with a group of European parliamentarians in early November. I and other Back Benchers had six minutes to speak in the debate. Given that the Conservative and Labour leadership agree on the policy towards Israel but are out of tune with the views in the country, such limited time for Back-Bench dissent is unhealthy, but it is the reality that the House of Commons has experienced during the terrible crisis in Gaza. I had a letter from a member of the public who was much distressed by events in Gaza. He watched the whole of the topical debate and was shocked that it ended with no vote and no action. I agree with him that the debate on Gaza demonstrated the weak and increasingly feeble state of the House of Commons. During our visit to Gaza, we witnessed the shortages of food, paper and pens in the United Nations Relief and Works Agency schools, and shortages of water, pharmaceuticals and other medical necessities. Even more dreadful, the sewage systems are not adequate. Raw sewage is pumped into the sea. There are plans for new sewage treatment plants, civil engineers are available and donors' funds have been committed, but Israel will not permit the materials to be imported. When it rains, sewage floods into people's homes, and because the Israeli navy fire on the fishermen if they go beyond a five-mile limit, hungry people eat polluted fish and are constantly ill. Half the children of Gaza are anaemic, and, even before the recent bombardment, large numbers were severely traumatised by the endless threat of violent attack. Israel also controls the import of EU-provided fuel for the power plant that gives light and power to Gaza. As everyone knows, Israel has partly bombed the power plant, but, as we left, it blocked all imports of fuel, and Gaza was cast into almost total darkness. The hospitals were run-down and lacking materials even before the terrible strains of coping with the injured from the three weeks of bombardment that have just ended. Gaza is a prison. It is a large, crowded Bantustan of 1.5 million people on a strip of land 25 miles by six or seven. Seventy per cent. of them are refugees who were ethnically cleansed by the Israelis from other parts of Palestine. Half of them are children. Israel withdrew its settlements in September 2005, but it controls the borders and access to the sea and air. It has bombed the airfield, which therefore cannot be used. Young people with scholarships cannot get out to take up their places, and sick people who cannot be treated locally cannot get out for medical care. Gaza is a prison-and that, of course, is why the tunnels exist. We went to Rafah to see them. Yes, some explosives may come through, but mostly what comes through are the necessities of life. British prisoners in Nazi prisoner-of-war camps built tunnels; Sarajevo built a tunnel-imprisoned people build tunnels. Now Israel has destroyed Rafah and the tunnels. It wants complete control of Gaza and for the people to lie down abjectly and accept their imprisonment. The tightening of the siege with full support from the EU, the UK and the US was the result of the Palestinian people daring to vote in internationally scrutinised elections for a majority of Hamas parliamentarians in January 2006. Following that, the Palestinians formed a Government of national unity, but Israel, supported by the US, did not want that. It is a matter of record that the policy supported by the UK was to incite division between Fatah and Hamas and to support fighting in Gaza. I understand that Britain supplied arms to the Fatah forces-that comes from authoritative sources. In response, Hamas took over Gaza. UNRWA staff told us how much safer life was without the conflict and roadblocks, but then the world besieged Gaza, imposing collective punishment on the people. That is an offence in international law, which lays down how people should be treated in occupied territories, but, as I said, none of the high contracting parties to the Geneva convention, including the UK, stand up for international law in the occupied Palestinian territories.
Andrew Smith (Lab): I have listened with great interest to the description of the awful humanitarian situation in Gaza. Is it the case that the readiness to ensure that breaches of international law and alleged war crimes are investigated and prosecuted is critical not only to the future of the middle east, obviously, but to our many constituents who care about the matter, especially those in the Muslim community, and much more widely as well? The perception of double standards damages the prospects for international peace and can also sour relations between the Islamic world in general and the rest of the community. Building bridges by ending those double standards is critical for the way forward internationally and for solidarity at home.
Clare Short (Independent): I agree absolutely with my right hon. Friend. I will come to that point and make that argument. It is the duty of parliamentarians and the public in the UK, and across Europe, to hold our Governments to account. The fact that they do nothing to enforce international law is a green light to Israel to keep breaking international law. The people of this country, particularly young Muslims, are angry about that and see our Government as engaged in double standards. That causes rage everywhere. We are told that the bombardment of Gaza was necessary because Israel has a right of defence against Hamas rockets. That justification of the attack is deeply dishonest. It is as big an untruth as were the claims about the need for war in Iraq. Two sets of facts are important when we assess Israel's excuse for its attack. For the past seven years, from when rocket attacks began up to 27 December when Israel attacked Gaza, those rockets killed 13 innocent Israelis and one foreigner. In that time, Israel killed 2,990 Palestinians in the Gaza strip, 634 of them children. Large numbers of those killed were innocent civilians, including many women and children. Those figures are provided by the Israeli human rights organisation, B'Tselem. There is no possible justification for us to say that Gaza was attacking Israel and Israel was not doing anything. The balance of attack and killing was that Israel was doing more harm to Gaza than the other way around. A way to stop rocket attacks was available without the bombardment. Negotiations had led to a halt to them. Egypt negotiated a six-month ceasefire from June 2008, which Hamas held to, and the rocket attacks stopped. But then, breaching the terms of the ceasefire, Israel tightened the siege and, in early November, it broke the ceasefire with a bombing attack that killed six Hamas members. Let us be clear: Israel kills massively more innocent Gazans than vice versa and negotiations had stopped the rockets. There was no case for Israel's attack, which was clearly long-planned. What is to be done about this dreadful situation that we are now in? All who defend Israel's position say that we must get back to the peace process, but the truth is that there is no peace process. Western policy is to divide and rule the Palestinians and, even though President Abbas and his Fatah faction do all that is asked of them, no concessions are made and the situation of the Palestinians on the ground gets worse still. It is clear, from the facts on the ground, that Israel has no intention of allowing the Palestinians their state on the lands that belong to them under international law and were occupied by Israel in 1967. In the Jordan valley, in East Jerusalem and on the west bank, massive settlements and small settlements established by extremists but protected by Israeli forces stand alongside the wall, which takes an illegal route. In addition, the closures and the Israeli-only roads show that Israel is taking still more land and confining the Palestinians to a series of Bantustans, where they are locked in and constantly humiliated if they try to move, and economic activity is steadily crushed. Prime Minister Olmert said that without two states there would be an international demand for an end to this apartheid system. Indeed, many South Africans, including Archbishop Tutu, have said that the situation is like apartheid in South Africa, only more brutal. Therefore, there are ever more calls for one state Â for all the people of Palestine, in which Jews and Palestinians, Israelis, Arabs and Christians would live side by side. But of course the demography shows, as Prime Minister Olmert pointed out, that Israelis would soon be in a minority. He said that there should be two states, but he does nothing to bring about two states. I conclude, with many others, that the two-state possibility is almost certainly dead. That means a long period of conflict and that, internationally, we must mount another boycott, divestment and sanctions campaign across the world. That will take time and create great division, but if our Governments will not stand up for decency and international law, then the people must do so.
Geoffrey Clifton-Brown (Con): I have a great deal of respect for the right hon. Lady, but does she not agree that all the international community has now more or less agreed that there should be a two-state solution? Is it not now up to the international community? It is up to Americans to pressurise the Israelis and whoever has influence with the Arabs, particularly Iran, to talk to them and make sure that this never happens again. Then we can get back to the peace process, put in the aid that is needed to rebuild Gaza, and, hopefully, we will not have this situation again.
Clare Short (Independent): I agree with the hon. Gentleman that the two-states idea is the answer, but it is eroding on the ground and no one is doing anything-including our Government and the hon. Gentleman's party's Front Bench. No one is standing by international law, which says that the lands occupied in 1967 cannot be incorporated into Israel and should be the basis for a Palestinian state. That is the answer, but it is disappearing. The world should be more troubled by that and should take more action to restrain Israel. That is the argument that I am trying to make. Those who are briefed by Israeli sources tell us, as do the Government and the Opposition Front Benches, that Hamas is a terrorist organisation that refuses to recognise Israel, refuses to accept previous agreements that have been negotiated and refuses to end violence. Our delegation met Prime Minister Haniya when we were in Gaza and he said that Hamas had answered each of those demands. It had ended violence by agreeing to and standing by the ceasefire, as I have described. It recognises that the Palestine Liberation Organisation had made agreements-notably, Oslo-and thought that, although it was a bad agreement, it was properly made. I agree that that is a bad agreement and that the Palestinians have lost out on it, because it has not been completed. Hamas also said that it would recognise a long-term peace if Israel would recognise a Palestinian state on 1967 boundaries. It has met the demands of the international community, but the international community is not interested, will not meet and discuss the matter, and will do nothing to restrain Israel and hold it to account under international law. I am afraid that the truth is that Israel does not recognise the Palestinian right to a state, as their reservations on the road map make clear. It is on the record that Israel certainly has not renounced violence and does not comply with Oslo or the road map, in that it will not allow a Palestinian state to be established. My request to the Government is that they cease their unbalanced policy and stand up for international law, on the basis of which we could achieve peace. I ask the Government, first, to halt all arms sales to Israel immediately. There is little doubt that British-supplied arms helped to kill people, including children, in Gaza. Arms sales should be halted. Secondly, the Government have said that the allegations of war crimes during the attack on Gaza must be investigated. There are serious allegations from very authoritative sources. I have taken legal advice on this matter, along with Baroness Tonge in the other place, which I am sending to all Members of Parliament in the UK. We will also circulate it across Europe. Briefly, that advice is that, because Israel did not sign up to the jurisdiction of the International Criminal Court, it is necessary for the Security Council to fulfil the role envisaged for it when the Rome statute of the ICC was concluded in 1998. That statute provided that, when some suspects were not from states that were parties to the treaty, instead of a special ad hoc tribunal, as in Rwanda and Yugoslavia, the Security Council should refer the case to the ICC, as in the case of Darfur. There have been serious allegations of war crimes, so it is right that all such allegations against all sides should be thoroughly investigated. I challenge the Government to refer the case to the ICC through the Security Council. Then we will see whether President Obama is going to stand up for international law and for the prospects for peace in the middle east, and abandon the US policy of vetoing all resolutions that in any way criticise Israel. An honourable Britain would do that. Following on from that point, sadly, although the Foreign Secretary and Lord Malloch-Brown have said that all allegations of war crimes must be investigated, Amnesty International informs me that it is widely believed that the UK, in the European Council of Ministers, is not being supportive of proposals for investigations into violations of international law because that would set a dangerous precedent for UK military operations across the world. That is shocking. Are UK Ministers saying one thing in Parliament and another in Brussels? If the Minister cannot answer fully now, I hope that she will ensure that the Government's explanation is made available quickly. In addition, the European Union has a trade treaty with Israel that gives it privileged access to EU markets. That treaty contains human rights conditionalities. Israel, even before the attack on Gaza, was in constant breach of the Geneva convention in its behaviour in the occupied territories, as the International Court of Justice spelled out in its 2004 advisory opinion. The route of the wall, the settlements, the closures and much else are a litany of breaches of international law, about which nothing is done. I want to know why the Government and the rest of the European Union do not invoke the conditionalities in the treaty to require Israel to abide by international law. Instead, the EU proposes enhancing its relationship with Israel. The message is clear-that Israel can go on gravely breaching international law and no action will be taken. Then we have the Geneva convention. It imposes duties on all high contracting parties to take action to impose its provisions for the treatment of people in occupied territories, yet the UK does nothing. My conclusion is that UK policy is completely unbalanced, fails to uphold international law and therefore sends a constant green light to Israel to do as it wishes. As my right hon. Friend the Member for Oxford, East (Mr. Smith) said, that is a shocking example of double standards and hypocrisy. It is also a recipe for continuing conflict in the middle east and the erosion of international order. I and others have been consulting lawyers about whether we can take action to require our Government to comply with international law and to require the EU to invoke the human rights conditionalities in the trade treaty. I am told that the tradition of our courts is that they do not interfere in foreign policy, but I suggest that we must take this further. If the Government will not uphold their duties under international treaties and the Geneva convention, and as Parliament has no power in this matter, surely it is time for the courts to act.
Gillian Merron (Lab): I welcome the debate and congratulate the right hon. Member for Birmingham, Ladywood (Clare Short) on securing it, because it provides a further opportunity for hon. Members to discuss the situation following the ceasefire. I should like to pick up on some general points and, if time permits, to refer to some of the specific points that she made.
Gillian Merron (Lab): Thank you, Mr. Hancock. The UK was active both in private and in public in working for a ceasefire. With our support, the UN Security Council, on 27 December, called for an immediate halt to the fighting. That was followed by intensive work by my right hon. Friends the Prime Minister and the Foreign Secretary with their international counterparts to deliver the ceasefire. The focus of international efforts now, rightly, is to ensure that the ceasefire holds. Without doubt the end of the hostilities will be welcomed most by the people of Gaza. We see day in, day out on our television screens the extent of the humanitarian tragedy caused by the fighting. To meet the urgent and profound humanitarian needs of the Palestinian people, on Monday the Prime Minister announced the trebling of the UK's humanitarian budget for Gaza, with an additional Â£20 million in aid to support the International Committee of the Red Cross to supply medical services. It will also deliver food, fuel and vehicles, and support desperately traumatised children. The UK is acting to stabilise unexploded bombs and, in the longer term, to help to rebuild destroyed homes. The UK also provides long-term support to the Palestinian people. In December 2007, we announced Â£243 million in aid over three years. It is without doubt early days, but the ceasefires declared by Israel on Saturday and Hamas on Sunday, although fragile, appear to be holding. We welcome the announcement by Israel in the past 24 hours that its troops have now completely withdrawn from Gaza. The Hamas ceasefire must be accompanied by immediate action to ensure that there are no further rocket attacks into Israel. More than 300 rockets and mortars were fired into Israel between June and December, and a further 300 rockets were fired at civilian Israeli targets over an eight-day period.
Geoffrey Clifton-Brown (Con): There is a desperate need to get food, water and medicines into Gaza. Will the Minister give us an assurance that the British Government will use every possible way to get that aid in as quickly as possible, if necessary by ships from the sea?
Gillian Merron (Lab): Indeed I can assure hon. Members that we are doing everything possible. As I said, we are working with our international counterparts and with organisations such as the ICRC. I will come on to the issue of support.

# Create opinon dataset for classification

In [17]:
OPINIONS= './../data/opinionated_sentences_uk_parliament.csv'
df_opinions=pd.read_csv(OPINIONS,names=["text"])

In [18]:
df_opinions["target"]="opinion"

In [19]:
df_opinions.head(10)

                                                text   target
0  It is my firm belief that unless this Governme...  opinion
1  In my judgement, the fiscal framework laid out...  opinion
2  I must express my deep concern that the propos...  opinion
3  It seems abundantly clear to me that the Gover...  opinion
4  I strongly believe that our border and immigra...  opinion
5  There is, in my view, a worrying complacency s...  opinion
6  It is painfully obvious that the deterioration...  opinion
7  I remain unconvinced that these educational re...  opinion
8  From my perspective, the proposed digital regu...  opinion
9  I must stress that any attempt to modernise ou...  opinion

In [26]:
#from df take 30 random samples, keeping the text only
df_samples=df.sample(n=30, random_state=42)[['instance_id',"text"]]

In [27]:
df_samples["target"]="non_opinionated"
df_samples.head(10)

,instance_id,text,target
1779227,1779338,"As he knows, we requested that advice in a wri...",non_opinionated
6382789,6382909,We do not want to be in the situation of askin...,non_opinionated
3741183,3741301,Friend the Member for Barnsley East (Michael D...,non_opinionated
4529679,4529797,If the Minister cannot be persuaded to make a ...,non_opinionated
2549893,2550006,Friend also seemed to suggest that it was a ba...,non_opinionated
530432,530481,â€The European Scrutiny Committee stated that...,non_opinionated
5047828,5047946,Many sociologists these days consider the conc...,non_opinionated
3699877,3699995,We need to look at the capacity that we have a...,non_opinionated
3992428,3992546,"If Scunthorpe magistrates court closes, howeve...",non_opinionated
402703,402747,The Government resisted open-access for many y...,non_opinionated

In [29]:
#print all the text from df_samples formatting it in a readable way
for index, row in df_samples.iterrows():
    print(f" Text: {row['text']}\n, id: {row['instance_id']}\n")

 Text: As he knows, we requested that advice in a written parliamentary question last week.
, id: 1779338

 Text: We do not want to be in the situation of asking for another extension and, of course, for the requirement to undertake European Parliament elections.
, id: 6382909

 Text: Friend the Member for Barnsley East (Michael Dugher), the shadow Transport Secretary, has said, these are simple procedures but they make a big difference to people.
, id: 3741301

 Text: If the Minister cannot be persuaded to make a permanent change to the rules, surely he will consider a change to last for the duration of the current crisis.
, id: 4529797

 Text: Friend also seemed to suggest that it was a bad thing for newspapers to make corrections and put right errors, but in all the difficult negotiations we have had the press did not raise this as a problem; indeed, it is what the PCC already does.
, id: 2550006

 Text: â€The European Scrutiny Committee stated thatâ€œwe are disappointed that Member States, in the ECOFIN Council and in the European Council, intend to continue to press on precipitately with this legislation and that the Government seems content to acquiesce in this haste.â€Will the Exchequer Secretary indicate whether the Government are content, if no agreement is reached tomorrow, to push the conclusion of this debate into next year in the interests of better scrutiny?
, id: 530481

 Text: Many sociologists these days consider the concept of life course, and my casework involves people right across the age range.
, id: 5047946

 Text: We need to look at the capacity that we have across the system to do more.
, id: 3699995

 Text: If Scunthorpe magistrates court closes, however, not a single court will remain in the unitary authority of North Lincolnshire.
, id: 3992546

 Text: The Government resisted open-access for many years.
, id: 402747

 Text: I can assure the hon.
, id: 1241881

 Text: He is absolutely right to point out the increase in employment, including in manufacturing employment.
, id: 2093033

 Text: partner-for Bath in his enthusiasm for specific sports, but some will obviously be more attractive than others.
, id: 1395879

 Text: I am very proud of the number of primary schools that have been expanded and rebuilt in my constituency.
, id: 5534816

 Text: I congratulate the hon.
, id: 892508

 Text: The Work Foundation has published a report called â€œManufacturing and the Knowledge Economyâ€.
, id: 99023

 Text: Order.
, id: 3995446

 Text: I thought we might have been in a position to debate where to go next, but unfortunately, despite it being the new year, we did not hear anything new from the Minister, just the same tired old Tory lines, which was disappointing.
, id: 3040853

 Text: In principle, on that basis, we are prepared to consent to new fracking proposals for shale gas if all other necessary permissions and consents are in place.
, id: 2372336

 Text: Does my hon.
, id: 5978166

 Text: It quickly became apparent that the huge rises in fuel prices had driven the achieving of our targets off course.
, id: 160202

 Text: It cannot just be about ticking boxes.
, id: 3742047

 Text: Friend on securing this debate and raising important issues about the barriers to good care that a lack of the right supported housing can lead to for people with learning disabilities and mental illness.
, id: 4586726

 Text: I repeat what was going to be my final point.
, id: 1904057

 Text: I am pretty sure that British taxpayers would much prefer their money to be spent on British food.
, id: 963539

 Text: Member for Stroud (Dr Drew), back to this place and back to this wonderful brief, DEFRA, where we have so many complex issues to deal with.
, id: 5133902

 Text: Perhaps I can come back to him on that point.
, id: 2225255

 Text: As always, there is logic in what my hon.
, id: 3578705

 Text: Of course, we have moved forward in terms of a resolution scheme between banks and businesses-with the dispute resolution service-and much of that I attribute to the hard work of the Minister, but there are limitations with that.
, id: 6518032

 Text: In fact, I apologise in advance for making a longer speech than I am accustomed to, because of so many such complexities, building warrants being just one of them.
, id: 5978702

In [30]:
removed_ids=[4586726, 963539, 6518032, 160202, 2372336, 3040853, 5534816]  # example ids to remove and to be replaced with other random samples
df_final_samples=df_samples[~df_samples['instance_id'].isin(removed_ids)]
new_samples=df.sample(n=len(removed_ids), random_state=24)[['instance_id',"text"]]
new_samples["target"]="non_opinionated"
df_final_samples=pd.concat([df_final_samples, new_samples], ignore_index=True)

,instance_id,text,target
0,1779338,"As he knows, we requested that advice in a wri...",non_opinionated
1,6382909,We do not want to be in the situation of askin...,non_opinionated
2,3741301,Friend the Member for Barnsley East (Michael D...,non_opinionated
3,4529797,If the Minister cannot be persuaded to make a ...,non_opinionated
4,2550006,Friend also seemed to suggest that it was a ba...,non_opinionated
5,530481,â€The European Scrutiny Committee stated that...,non_opinionated
6,5047946,Many sociologists these days consider the conc...,non_opinionated
7,3699995,We need to look at the capacity that we have a...,non_opinionated
8,3992546,"If Scunthorpe magistrates court closes, howeve...",non_opinionated
9,402747,The Government resisted open-access for many y...,non_opinionated
10,1241881,I can assure the hon.,non_opinionated
11,2093033,He is absolutely right to point out the increa...,non_opinionated
12,1395879,partner-for Bath in his enthusiasm for specifi...,non_opinionated
13,892508,I congratulate the hon.,non_opinionated
14,99023,The Work Foundation has published a report cal...,non_opinionated
15,3995446,Order.,non_opinionated
16,5978166,Does my hon.,non_opinionated
17,3742047,It cannot just be about ticking boxes.,non_opinionated
18,1904057,I repeat what was going to be my final point.,non_opinionated
19,5133902,"Member for Stroud (Dr Drew), back to this plac...",non_opinionated
20,2225255,Perhaps I can come back to him on that point.,non_opinionated
21,3578705,"As always, there is logic in what my hon.",non_opinionated
22,5978702,"In fact, I apologise in advance for making a l...",non_opinionated
23,686923,That policy is now under threat from the Torie...,non_opinionated
24,962065,"Shortly before my election to the House, I was...",non_opinionated
25,2101107,That brings me to the many points that have be...,non_opinionated
26,2621070,"We are in unprecedented conditions, and it is ...",non_opinionated
27,568347,"If a farmer could lose large areas of land, fo...",non_opinionated
28,5149546,It is fitting that we should do so as we are a...,non_opinionated
29,6211687,My hon.,non_opinionated

In [32]:
df_final_samples.drop('instance_id', axis=1, inplace=True)

In [34]:
dataset = pd.concat([df_final_samples, df_opinions], ignore_index=True)
dataset = dataset.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle the dataset
dataset.to_csv('./../data/opinion_dataset.csv', index=False)